name: Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest  # Linux runner

    steps:
      # Stap 1: Checkout de code uit de repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Stap 2: Setup Docker Buildx (voor multi-platform build en caching)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Stap 3: Log in op Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Stap 4: Build en push de Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: yourdockerhubusername/your-image-name:latest
